[build]
  functions = "netlify/functions"
  publish = "."

[dev]
  framework = "#static"
  functions = "netlify/functions"
  publish = "."
  port = 9999

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/avatar/*"
  to = "/.netlify/functions/get-avatar"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200